version: '3'
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "1qaz2wsx"
            MYSQL_DATABASE: "NOTAFISCAL"
        ports:
            - "3306:3306"
        volumes:
            - ./data/:/var/lib/mysql