USE `NOTAFISCAL`;
DROP procedure IF EXISTS `POPULANF`;

DELIMITER $$
USE `NOTAFISCAL`$$
CREATE DEFINER=`root`@`%` PROCEDURE `POPULANF`()
BEGIN
    DECLARE VCONTADOR INT;
    DECLARE VDATACADASTRO DATE;
    
    SET VCONTADOR = 1;
    SET DATACADASTRO = (SELECT DATE_SUB(DATE(NOW()), INTERVAL 10 DAY));
    
    WHILE VCONTADOR <= 1000 DO
        
        INSERT INTO EXAME_NF (IDNF, NUMERO, DATACADASTRO, TOTALGERAL) VALUES ( NULL, VCONTADOR, DATACADASTRO, 3);
        
        INSERT INTO EXAME_ITEM_NF (IDITEMNF, IDNF, IDPRODUTO, QTDE, VALOR) VALUES 
            ( NULL, VCONTADOR, RAND(), 1, 1),
            ( NULL, VCONTADOR, RAND(), 1, 1),
            ( NULL, VCONTADOR, RAND(), 1, 1);
        
        IF (MOD(VCONTADOR, 100) = 0) THEN
            SET DATACADASTRO = DATE_ADD(DATACADASTRO, INTERVAL 1 DAY);
        END IF;
        
        SET VCONTADOR = VCONTADOR + 1;
    END WHILE;
    
END$$

DELIMITER ;

