a) SELECT * FROM PRODUTO LIMIT 10;

b) SELECT PRODUTO.* FROM PRODUTO
    RIGHT JOIN EMBALAGEM ON PRODUTO.IDPRODUTO=EMBALAGEM.IDPRODUTO
    GROP BY PRODUTO.IDPRODUTO;

c) SELECT 
    PRODUTO.DESCR AS PRODUTO, 
    (SELECT COUNT(EMBALAGEM.IDPRODUTO) 
      FROM EMBALAGEM 
      WHERE EMBALAGEM.IDPRODUTO=PRODUTO.IDPRODUTO) AS QUANT_EMBALAGEM
  FROM PRODUTO;

d) INSERT INTO `senior`.`PRODUTO` (`IDPRODUTO`, `CODIGOINTERNO`, `DESCR`, `ATIVO`) VALUES 
('99', '6', 'OLEO DE MILHO', 'S');

INSERT INTO `senior`.`EMBALAGEM` (`IDPRODUTO`, `BARRA`, `DESCR`, `FATORCONVERSAO`, `ALTURA`, `LARGURA`, `COMPRIMENTO`,`ATIVO`) VALUES 
('99', '7891000315512', 'OLEO DE MILHO LT', '1', '200', '100', '100', 'S'),
('99', '7891000315513', 'OLEO DE MILHO CX COM 10', '10', '250', '400', '400', 'S');


e) UPDATE EMBALAGEM SET ALTURA=250, LARGURA=120, COMPRIMENTO=150 WHERE FATORCONVERSAO=1;